package dk.itu.moapd.copenhagenbuzz.fcag.dbOperations

import android.util.Log
import android.view.View
import com.google.android.material.snackbar.Snackbar
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.database.DataSnapshot
import com.google.firebase.database.DatabaseError
import com.google.firebase.database.ValueEventListener
import com.google.firebase.database.ktx.database
import com.google.firebase.ktx.Firebase
import com.google.firebase.storage.ktx.storage
import dk.itu.moapd.copenhagenbuzz.fcag.data.Event
import dk.itu.moapd.copenhagenbuzz.fcag.data.EventLocation
import dk.itu.moapd.copenhagenbuzz.fcag.locationServices.Geocoding
import io.github.cdimascio.dotenv.dotenv
import kotlinx.coroutines.MainScope
import kotlinx.coroutines.launch

class CrudOperations {

    // A set of private constants used in this class.
    companion object {
        private var TAG = "CrudOperations"
    }


    // Environment Variables
    private val dotenv = dotenv {
        directory = "/assets"
        filename = "env"
    }
    private val DATABASE_URL = dotenv["DATABASE_URL"]
    private val BUCKET_URL = dotenv["STORAGE_URL"]


    // Initializing variables used in this class
    private var geocode = Geocoding()





    /**
     * Adds an event to the Firebase Realtime Database under a specific user's "events" node.
     * This function assigns a unique ID to the event, which is generated by Firebase's push method.
     * It also attaches the user's UID to the event as the `userId`.
     * Successful or failed additions are indicated through Snack bar messages.
     *
     * @param event The event object to be added to the database.
     * @param view The view used to anchor the Snack bar for displaying messages.
     */
     fun addEventToFirebase(event: Event, view: View) {
        val databaseReference = Firebase.database(DATABASE_URL).reference.child("copenhagen_buzz")

        val userId = FirebaseAuth.getInstance().currentUser?.uid
        event.userId = userId   // Assign user ID to the event

        // Generate a unique key for the event under the 'events' child of 'copenhagen_buzz'
        val key = userId?.let {
            databaseReference.child("events")
                .child(it)
                .push()
                .key
        }


        event.eventId = key // Assign the generated key as the event's ID


        if (key != null) {
            databaseReference.child("events").child(userId).child(key).setValue(event)
                .addOnSuccessListener {
                    Log.d(TAG, "Event added successfully")
                    Snackbar.make(
                        view,
                        "Event added successfully",
                        Snackbar.LENGTH_SHORT
                    ).show()
                }
                .addOnFailureListener { e ->
                    Log.e(TAG, "Failed to add event", e)
                    Snackbar.make(
                        view,
                        "Failed to add event",
                        Snackbar.LENGTH_SHORT
                    ).show()
                }
        }
    }







    /**
     * Adds an event to the user's "favorites" node in the Firebase Realtime Database.
     * The event is identified by its existing eventId. If the event ID and user ID are valid,
     * the event is added as a favorite under the user's UID.
     * Successful or failed additions are indicated through Snack bar messages.
     *
     * @param event The event object to be added to the favorites.
     * @param view The view used to anchor the Snack bar for displaying messages.
     */
    fun addFavoriteToFirebase(event: Event, view: View) {
        val databaseReference = Firebase.database(DATABASE_URL).reference.child("copenhagen_buzz")
        val userId = FirebaseAuth.getInstance().currentUser?.uid
        val key = event.eventId

        userId?.let {
            databaseReference.child("favorites")
                .child(it)
                .push()

        } // Generate a unique key for the event


        if (key != null) {
            if (userId != null) {
                databaseReference.child("favorites").child(userId).child(key).setValue(event)
                    .addOnSuccessListener { _ ->
                        Log.d(TAG, "Added to favorites")
                        Snackbar.make(
                            view,
                            "Added to favorites",
                            Snackbar.LENGTH_SHORT
                        ).show()
                    }
                    .addOnFailureListener { e ->
                        Log.e(TAG, "Failed to add to favorites", e)
                        Snackbar.make(
                            view,
                            "Failed to add to favorites",
                            Snackbar.LENGTH_SHORT
                        ).show()
                    }
            }
        }
    }








    /**
     * Deletes an event from the Firebase Realtime Database and its associated image from Firebase Storage.
     * The function targets three specific operations:
     * 1. Removing the event from the 'events' node.
     * 2. Removing the event from the 'favorites' node.
     * 3. Deleting the event's image from Firebase Storage.
     * Each operation logs a success or failure message.
     *
     * If both the event and its image are successfully deleted, a confirmation message is
     * displayed to the user via a Snack bar.
     *
     * @param event The event object to be deleted, containing necessary identifiers like eventId and eventPhotoUrl.
     * @param view The view used to anchor the Snack bar for displaying messages.
     */
    fun deleteFromFirebase(event: Event, view: View) {
        val key = event.eventId
        var deletedFromEvents = false

        key?.let {
            FirebaseAuth.getInstance().currentUser?.uid?.let { userId ->
                // Delete from events
                Firebase.database(DATABASE_URL).reference.child("copenhagen_buzz")
                    .child("events")
                    .child(userId)
                    .child(it)
                    .removeValue()
                    .addOnSuccessListener {
                        Log.d(TAG, "Successfully deleted from events")
                        deletedFromEvents = true
                    }
                    .addOnFailureListener { e ->
                        Log.w(TAG, "Failed to delete from events", e)
                    }

                // Delete from favorites
                Firebase.database(DATABASE_URL).reference.child("copenhagen_buzz")
                    .child("favorites")
                    .child(userId)
                    .child(it)
                    .removeValue()
                    .addOnSuccessListener { _ ->
                        if (deletedFromEvents) {
                            Log.d(TAG, "Event successfully deleted")
                            Snackbar.make(view, "Event successfully deleted", Snackbar.LENGTH_SHORT).show()
                        }
                    }
                    .addOnFailureListener { e ->
                        Log.w(TAG, "Failed to delete event.", e)
                    }


                // Delete Image
                event.eventPhotoUrl?.let { it ->
                    Firebase.storage(BUCKET_URL).reference.child("event").child(userId).child(it).delete()
                        .addOnSuccessListener {
                            Log.d(TAG, "Photo deletion successful")
                        }
                        .addOnFailureListener {
                            Log.e(TAG, "Error getting photo URL", it)
                        }
                }
            }
        }
    }










    /**
     * Updates the details of an existing event in Firebase based on provided new details.
     *
     * This function takes an `Event` object and updates its details such as name, location, date,
     * type, and description in the Firebase database.
     *
     * The location is updated based on the geocoding of a new address if it differs from the
     * existing one. If the location fetching fails, it displays a snack-bar message on the
     * provided `View`.
     *
     * The event details are updated in both the main events database and the favorites section if
     * the event is marked as a favorite.
     *
     * Successful and error states are communicated via snack-bar messages.
     *
     * @param event An instance of `Event` containing the current event details including a unique event ID.
     * @param view The `View` used to show snack-bar messages for success or failure notifications.
     * @param newName The new name for the event.
     * @param newLocation The new location for the event as a plain address string, which will be geocoded to get location coordinates.
     * @param newDate The new date for the event.
     * @param newType The new type of the event.
     * @param newDescription The new description of the event.
     */
    fun updateEventInFirebase(event: Event, view: View, newName: String, newLocation: String, newDate: String, newType: String, newDescription: String) {
         val key = event.eventId

         MainScope().launch {
             // Initialize location
             var location = event.eventLocation ?: EventLocation()

             // Check if location needs to be updated
             if (event.eventLocation?.address != newLocation) {
                 try {
                     location = geocode.getLocationCoordinates(newLocation)
                 } catch (e: Exception) {
                     Snackbar.make(view, "Failed to fetch location", Snackbar.LENGTH_SHORT).show()
                     return@launch
                 }
             }


             key?.let {
                 FirebaseAuth.getInstance().currentUser?.uid?.let { userId ->

                     // Creating a map to hold the updated values
                     val updateValues = mapOf(
                         "eventName" to newName,
                         "eventLocation" to location,
                         "eventDate" to newDate,
                         "eventType" to newType,
                         "eventDescription" to newDescription
                     )

                     // Update Events Database
                     Firebase.database(DATABASE_URL).reference.child("copenhagen_buzz")
                         .child("events")
                         .child(userId)
                         .child(it)
                         .updateChildren(updateValues)

                         .addOnSuccessListener {
                             Snackbar.make(
                                 view,
                                 "Event updated successfully",
                                 Snackbar.LENGTH_SHORT
                             ).show()
                         }
                         .addOnFailureListener {
                             Snackbar.make(view, "Failed to update event", Snackbar.LENGTH_SHORT)
                                 .show()
                         }


                     // Update favorites Database, only if favorite event is present.
                     val favoriteReference =
                         Firebase.database(DATABASE_URL).reference.child("copenhagen_buzz")
                             .child("favorites")
                             .child(userId)
                             .child(it)


                     favoriteReference.addListenerForSingleValueEvent(object : ValueEventListener {
                         override fun onDataChange(snapshot: DataSnapshot) {
                             if (snapshot.exists()) {
                                 // Event exists, you can proceed with update or show confirmation
                                 favoriteReference.updateChildren(updateValues)
                             } else {
                                 // Event does not exist, show a message or handle accordingly
                                 Log.d(TAG, "Event does not exist")
                             }
                         }

                         override fun onCancelled(error: DatabaseError) {
                             Snackbar.make(view, "Error: $error", Snackbar.LENGTH_SHORT).show()
                         }
                     })
                 }
             }
         }
     }



}